apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: la2bl90gs-go 
  janus-idp.io/tekton: la2bl90gs-go
  backstage.io/kubernetes-id: la2bl90gs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: la2bl90gs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml