apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: la2bl90gs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: la2bl90gs-go 
  name: la2bl90gs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: la2bl90gs-go 
